name: Publish Docker images to GitHub Packages

on:
  push:
    branches:
      - main

jobs:

  build-and-push-image-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Packages registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for bot
        run: |
          docker build -f Dockerfile -t key-cycle-proxy .

      - name: Tag and push bot image
        run: |
          docker tag key-cycle-proxy:latest ghcr.io/berry-13/key-cycle-proxy:${{ github.sha }}
          docker push ghcr.io/berry-13/key-cycle-proxy:${{ github.sha }}
